# Generated by Django 3.1.5 on 2021-06-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.CharField(max_length=50, verbose_name='url')),
                ('description', models.CharField(max_length=500, verbose_name='desciption')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'category ',
                'verbose_name_plural': 'categorys',
            },
        ),
        migrations.AlterModelOptions(
            name='article_model',
            options={'verbose_name': 'Article ', 'verbose_name_plural': 'Articles'},
        ),
    ]
