# Generated by Django 3.1.5 on 2021-06-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210609_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_model',
            name='category',
            field=models.ManyToManyField(to='reviews.Category', verbose_name='category'),
        ),
    ]
