# Generated by Django 3.1.5 on 2021-06-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_article_model_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_model',
            name='status',
            field=models.CharField(choices=[(' P ', 'PUBLISH'), (' d ', 'DRAFT'), ('x', 'blog')], max_length=3, verbose_name='status'),
        ),
    ]
