# Generated by Django 3.1.5 on 2021-06-23 10:48

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20210618_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_model',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 6, 23, 10, 48, 58, 539800, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article_model',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='article_model',
            name='thumbnail',
            field=models.ImageField(upload_to='images', verbose_name='picture-url'),
        ),
    ]
