# Generated by Django 3.1.5 on 2021-06-23 11:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20210623_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_model',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 6, 23, 11, 0, 50, 322392, tzinfo=utc)),
        ),
    ]
