# Generated by Django 3.1.5 on 2021-06-27 08:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20210623_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_model',
            name='category',
            field=models.ManyToManyField(related_name='articles', to='reviews.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='article_model',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 6, 27, 8, 1, 46, 741179, tzinfo=utc)),
        ),
    ]
