# Generated by Django 3.1.5 on 2021-06-29 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20210627_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_model',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
